# Common
environment:
  vrs: 0.0.2

for:
# Developement
-
  version: $(vrs).{build}-dev
  branches:
    only:
      - develop
  skip_tags: true
  skip_branch_with_pr: true
  skip_commits:
    message: /(Bumped)|(\[release\])/i
  image: Visual Studio 2017
  configuration: Debug
  before_build:
    - ps: nuget restore src/Cport.sln
  build:
    verbosity: minimal
  test_script:
    - ps: dotnet test src/CPort.Tests/
  artifacts:
    - path: src/CPort/bin/$(configuration)/*.nupkg
      name: Nuget Packages
  
# Production
-
  version: $(vrs).{build}
  branches:
    only:
      - master
  skip_tags: true
  skip_branch_with_pr: true
  image: Visual Studio 2017
  configuration: Release
  before_build:
    - ps: nuget restore src/Cport.sln
  build:
    verbosity: minimal
  test: off
  artifacts:
    - path: src/CPort/bin/$(configuration)/*.nupkg
      name: Nuget Packages
  deploy:
    - provider: Environment
      name: Nuget

    - provider: GitHub
      #tag: $(appveyor_repo_tag_name)
      release: myproduct-v$(appveyor_build_version)
      description: 'Version $(vrs)'
      auth_token:
        secure: /8U4+qBT5wE6uiNtx4eBPGl8g8i7R8zH8BFcg6va7vgti6Qw/SqT0McVgqv4pc+k
      artifact: /.*\.nupkg/
      draft: true
      prerelease: false
      on:
        branch: master                 # release from master branch only
        appveyor_repo_tag: true        # deploy on tag push only
